SuperHero/Models/Hero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SuperHero.Models
{
    public class Hero
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string alterEgo { get; set; }
        public string primaryAbility { get; set; }
        public string secondaryAbility { get; set; }
        public string catchPhrase { get; set; }

    }
}

SuperHero/Controllers/HeroController.cs
using SuperHero.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperHero.Controllers
{
    public class HeroController : Controller
    {
        ApplicationDbContext context;
        public HeroController()
        {
            context = new ApplicationDbContext();
        }
        // GET: Hero
        public ActionResult Index()
        {
            return View();
        }

        // GET: Hero/Details/5
        public ActionResult Details(int id)
        {
            Hero hero = context.Heroes.Where(h => h.Id == id).FirstOrDefault();
            return View(hero);
        }

        // GET: Hero List/ List

        public ActionResult List()
        {
            List<Hero> heroList = context.Heroes.ToList();
            return View(heroList);
        }

        [HttpPost]
        public ActionResult List(List<Hero> heroList)
        {     
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        // GET: Hero/Create
        public ActionResult Create()
        {
            Hero hero = new Hero();
            return View(hero);
        }

        // POST: Hero/Create
        [HttpPost]
        public ActionResult Create(Hero hero)
        {
            try
            {
                context.Heroes.Add(hero);
                context.SaveChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        // GET: Hero/Edit/5
        public ActionResult Edit(int id)
        {
            Hero hero = context.Heroes.Where(h => h.Id == id).First();
            return View(hero);
        }

        // POST: Hero/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Hero hero)
        {
            try
            {
                context.Heroes.Remove(context.Heroes.FirstOrDefault(h => h.Id == hero.Id));
                context.Heroes.Add(hero);
                context.SaveChanges();
                return RedirectToAction("List");


                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //GET: Hero/Delete/5
        public ActionResult Delete(int id)
        {
            // Hero heroToDelete = context.Heroes.Where(hero => hero.Id == id).SingleOrDefault();
            Hero heroToDelete = context.Heroes.Find(id);

            return View( heroToDelete);
        }

        //POST: Hero/Delete/5
        [HttpPost]
        public ActionResult Delete( Hero heroToDelete)
        {
            try
            {

                context.Heroes.Remove(context.Heroes.FirstOrDefault(h => h.Id == heroToDelete.Id));
                context.SaveChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperHero/Views/Hero/Create.cshtml
@model SuperHero.Models.Hero

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hero</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.alterEgo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.alterEgo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.alterEgo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.primaryAbility, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.primaryAbility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.primaryAbility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.secondaryAbility, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.secondaryAbility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.secondaryAbility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.catchPhrase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.catchPhrase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.catchPhrase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SuperHero/Views/Hero/Delete.cshtml
@model SuperHero.Models.Hero

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hero</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.alterEgo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.alterEgo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.primaryAbility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.primaryAbility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.secondaryAbility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.secondaryAbility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.catchPhrase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catchPhrase)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SuperHero/Views/Hero/Details.cshtml
@model SuperHero.Models.Hero

<div>
    <h4>Hero</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.alterEgo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.alterEgo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.primaryAbility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.primaryAbility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.secondaryAbility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.secondaryAbility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.catchPhrase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catchPhrase)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "List","Hero")
</p>

SuperHero/Views/Hero/Edit.cshtml
@model SuperHero.Models.Hero


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hero</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.alterEgo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.alterEgo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.alterEgo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.primaryAbility, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.primaryAbility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.primaryAbility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.secondaryAbility, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.secondaryAbility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.secondaryAbility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.catchPhrase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.catchPhrase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.catchPhrase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SuperHero/Views/Hero/List.cshtml
@model IEnumerable<SuperHero.Models.Hero>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.alterEgo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.primaryAbility)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.secondaryAbility)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.catchPhrase)
        </th>
        <th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.alterEgo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.primaryAbility)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.secondaryAbility)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.catchPhrase)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>